/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GlassSurface: typeof import('./src/components/ui/GlassSurface.vue')['default']
    GradientText: typeof import('./src/components/ui/GradientText.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    PatternCard: typeof import('./src/components/pattern/PatternCard.vue')['default']
    PatternCodeBlock: typeof import('./src/components/pattern/PatternCodeBlock.vue')['default']
    PatternModal: typeof import('./src/components/pattern/PatternModal.vue')['default']
    PatternShowcase: typeof import('./src/components/pattern/PatternShowcase.vue')['default']
    PhoneFrame: typeof import('./src/components/pattern/PhoneFrame.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShinyText: typeof import('./src/components/ui/ShinyText.vue')['default']
    SparklesText: typeof import('./src/components/ui/SparklesText.vue')['default']
    SpecularButton: typeof import('./src/components/ui/SpecularButton.vue')['default']
  }
}
