/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GlassSurface: typeof import('./src/components/ui/GlassSurface.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    PatternCard: typeof import('./src/components/pattern/PatternCard.vue')['default']
    PatternCodeBlock: typeof import('./src/components/pattern/PatternCodeBlock.vue')['default']
    PatternModal: typeof import('./src/components/pattern/PatternModal.vue')['default']
    PatternShowcase: typeof import('./src/components/pattern/PatternShowcase.vue')['default']
    PhoneFrame: typeof import('./src/components/pattern/PhoneFrame.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SparklesText: typeof import('./src/components/ui/SparklesText.vue')['default']
    SpecularButton: typeof import('./src/components/ui/SpecularButton.vue')['default']
  }
}

// For TSX support
declare global {
  const GlassSurface: typeof import('./src/components/ui/GlassSurface.vue')['default']
  const Logo: typeof import('./src/components/Logo.vue')['default']
  const PatternCard: typeof import('./src/components/pattern/PatternCard.vue')['default']
  const PatternCodeBlock: typeof import('./src/components/pattern/PatternCodeBlock.vue')['default']
  const PatternModal: typeof import('./src/components/pattern/PatternModal.vue')['default']
  const PatternShowcase: typeof import('./src/components/pattern/PatternShowcase.vue')['default']
  const PhoneFrame: typeof import('./src/components/pattern/PhoneFrame.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SparklesText: typeof import('./src/components/ui/SparklesText.vue')['default']
  const SpecularButton: typeof import('./src/components/ui/SpecularButton.vue')['default']
}